### ISSUE TITLE
Add slide on boolean operations in introduction

### ISSUE THREAD

**Issue by LiamDBailey** [courtiol/LM2GLMM#32]
- Explain `==`, `!=` (also `&` and `|`?)
- Explain how logical responses can coerce to numeric (maybe show what happens if you use `sum()` on logical data)

**Comment by LiamDBailey** [comment]
Also needed because we use `mean()` on logical data in pg 4 of exercises

**Comment by courtiol** [comment]
Please combine with #30 into a single slide (perhaps 2 columns, as I did in places) and PR.
