### ISSUE TITLE
Add plot showing fitted values v. mean response values for simple linear model

### ISSUE THREAD

**Issue by LiamDBailey** [courtiol/LM2GLMM#33]
**LM_intro_course.Rmd:**

Around slide 26

**Comment by LiamDBailey** [comment]
For e.g.:

![PXL_20220607_133318929](https://user-images.githubusercontent.com/11307658/172394011-34f9c3d0-a5a8-454b-bc6a-024e5d130120.jpg)

**Comment by LiamDBailey** [comment]
![image](https://user-images.githubusercontent.com/11307658/172456468-1f6be5b2-dab8-4f06-bfb0-dda879b0a7b0.png)

**Comment by LiamDBailey** [comment]
A bit crude, but might be good enough for our purposes. Doesn't require any extra dependencies ({ggplot2} only)

**Comment by courtiol** [comment]
Thanks, that looks great. Please PR.
