### ISSUE TITLE
clarify what are demos from what are practical advices

### ISSUE THREAD

**Issue by courtiol** [courtiol/LM2GLMM#5]
To make it clearer for the students to understand what is there "just" to show them how things work from what they need to do in practice, I could perhaps split slides like that and use some graphical way to make it clear (different background? Different color for the titles?).

**Comment by courtiol** [comment]
We could use emojis:

- for aliens: `emojifont::emoji("alien")` :alien:
- for goals: `emojifont::emoji("dart")` :dart:
- for solutions or nice results: `emojifont::emoji("tada")` :tada:
- for things that are good to know: `emojifont::emoji("mortar_board")` :mortar_board:
- for practical advice: `emojifont::emoji("wrench")` :wrench:
- for things that are broken: `emojifont::emoji("angry")` :angry:
- for heavy computations: `emojifont::emoji("fire")` :fire:
- for warnings: `emojifont::emoji("warning")`  :warning:

**Comment by LiamDBailey** [comment]
FYI; Hadley's {{emo}} package (`r devtools::install_github("hadley/emo")`) has a wider variety of emojis than {{emojifont}}. As far as I can tell, every emoji in {{emojifont}} is in {{emo}} but not visa-versa

- 🎓 `r emojifont::emoji("mortar_board")` might be understood as 'information you *need to know* to pass the course' (i.e. graduate). Other alternatives could be:
    - ⭐️ `r emojifont::emoji("star")`
    - ⏫ `r emojifont::emoji("arrow_double_up")` it's like 'leveling up'
    - 🤓 `r emojifont::emoji("nerd_face")` don't *need to know* but includes some nerdy details to improve knowledge

- 👓 `r emojifont::emoji("eyeglasses")`. Other alternatives:
    - 👩‍🔬 `r emojifont::emoji("woman_scientist")` because you're teaching them how to experiment/test their own ideas.
    - 🥽 `r emo::ji("goggles")` same reasoning as above. This one doesn't work in emojifont
    - 🧪/⚗️ `r emo::ji("test_tube")`/`r emo::ji("alembic")` same reasoning as above

Will we need 😠 `r emojifont::emoji("angry")` for the students or this is just for us?

**Comment by courtiol** [comment]
I would rather not to use **{emo}** because it is not on CRAN and because the exact display of many emojis from this package is random (they have multiple instances and are drawn randomly).

I like the nerd face and would have like to use it but I don't think it is part of **{emojifont}** (that's too bad).
Yet, it seems I can just paste those emojis without using R call:
![image](https://user-images.githubusercontent.com/7499666/169030581-a8c4bdbd-1a2b-4b57-a4ba-9f56dbe4b4ad.png)

I worry that in such a case, the output depends on the fonts installed on your system. Do you know?

I consider everything good to know as required to pass the test but the most important things are labelled with :dart: 

So all in all I think that the only emoji I use that is not quite obvious enough is the :eyeglasses:.
Can you think of a better alternative in **{emojifont}** or shall I just paste 🧪 ?

**Comment by LiamDBailey** [comment]
From my (limited) understanding of emojis, because they are coded in Unicode then copy-pasting them should be no problem because all systems understand Unicode. However, the output will vary slightly by system (i.e. it's different between MacOS and Windows) because each system translates the underlying Unicode differently, but they should still be generally understandable. But anyway, for reproducibility I can see that using {{emojifont}} is preferable because it's on CRAN. In that case I would suggest some alternatives for the glasses:

- 🔬 `r emojifont::emoji("microscope")`
- ⚗️ `r emojifont::emoji("alembic")` (maybe a bit niche if they never did chemistry!)

**Comment by LiamDBailey** [comment]
Alternatively, seems you can also call print the unicode directly as ASCII characters and it will be converted to emoji when knitting (that's what I understand is happening anyway).

`r knitr::asis_output("\U1F97D")` = 🥽
`r knitr::asis_output("\U1F9EA")` = 🧪

I find all the emojis (and their underlying Unicode values) here: https://emojipedia.org/

**Comment by courtiol** [comment]
```r
.emo <- function(x = c("info", "practice", "proof", "goal", "party", "broken", "heavy", "warn", "alien")) {
  x <- match.arg(x)
  if(!requireNamespace("emojifont")) stop("You need to install the package emojifont to use this function.")
  switch (x,
    info = emojifont::emoji("mortar_board"),
    practice = emojifont::emoji("wrench"),
    proof = knitr::asis_output("\U1F9EA"),
    goal = emojifont::emoji("dart"),
    party = emojifont::emoji("tada"),
    broken = emojifont::emoji("angry"),
    heavy = emojifont::emoji("fire"),
    warn = emojifont::emoji("warning"),
    alien = emojifont::emoji("alien")
  )
}


> sapply(c("info", "practice", "proof", "goal", "party", "broken", "heavy", "warn", "alien"), .emo)
    info practice    proof     goal    party   broken    heavy     warn    alien 
    "🎓"     "🔧"     "🧪"     "🎯"     "🎉"     "😠"     "🔥"      "⚠️"     "👽" 
```

**Comment by LiamDBailey** [comment]
looks great

**Comment by courtiol** [comment]
OK, I will do that everywhere as I go! Thanks again.
