### ISSUE TITLE
Make it clear that we may need boxcox(y + lambda2) when `min(y) <= 0`

### ISSUE THREAD

**Issue by LiamDBailey** [courtiol/LM2GLMM#56]

**Comment by courtiol** [comment]
gamma seems different than discussed with @LiamDBailey :

```r
> car::bcnPowerInverse
function (z, lambda, gamma) 
{
    q <- if (abs(lambda) < 1e-07) 
        2 * exp(z)
    else 2 * (lambda * z + 1)^(1/lambda)
    (q^2 - gamma^2)/(2 * q)
}
```

**Comment by courtiol** [comment]
Well, it is  a little more complex, gamma is indeed lambda2 in `bcPower()` but there is no inverse function for that and the inverse function `bcnPowerInverse()` has a gamma parameter computed differently as that of  `bcPower()`. So to be as clear as possible, let's not use gamma.
